# Generated by Django 5.1 on 2024-08-11 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_alter_blogpost_date_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-date_posted'], 'verbose_name': 'Blog Post', 'verbose_name_plural': 'Blog Posts'},
        ),
    ]
