# Generated by Django 5.1 on 2024-08-14 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'About Me'},
        ),
    ]
