# Generated by Django 5.1 on 2024-08-14 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0007_alter_about_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'About Me', 'verbose_name_plural': 'About Me'},
        ),
    ]
